### ISSUE TITLE
Please help me, my github pages code block line can't wrap.

### ISSUE THREAD

**Issue by haiy** [streetturtle/streetturtle.github.io#1]
hi there,I just find your jekyll-clean-dark theme,that's great,I tried it but temporarily i think it's too hard for me to play it. Would you please help me to fix my github pages code block line can't wrap bug on my simple site, here is a sample the line outside the box,[here's my messed page](http://haiy.github.io/2016/07/13/%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0%E7%A1%AC%E4%BB%B6%E9%85%8D%E7%BD%AE%E5%8F%8A1080%E6%98%BE%E5%8D%A1%E5%AE%89%E8%A3%85.html).thanks so much for your help

**Comment by streetturtle** [comment]
@haiy Hi there! Unfortunately I don't have a laptop with me right now,  but I would guess that you need to put `word-wrap: break-word;` property to you text or something similar. Anyway I can have a look this weekend.

**Comment by haiy** [comment]
@streetturtle ,thanks for your suggestion, sadly I've already tried to add the property,either directly or its parent div,but it didn't work.So I was just stuck with it. It's very kind of you to help me, weekend is ok.

**Comment by haiy** [comment]
hi @streetturtle !I'm glad to tell you that I fix it finally. with a simple css setting, 

```
pre {
    white-space: pre-wrap;
}
```
